version: '3'

services:
  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/app1-go:{{ env.TAG }}
    ports:
      - $PORT:8080
    environment:
      - PORT=$APP_PORT
    volumes:
      - ./app:/app
    command: /app/main

