name: CD
on:
  push:
    branches: ["dev"]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Set up Docker Compose
        run: |
          # Завантаження нового Docker імеджу з Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app1-go:${{ env.TAG }}
          # Запуск Docker Compose
          docker-compose -f docker-compose.yaml up -d
        env:
          PORT: $APP_PORT




