name: CI 
on:
  push:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Validate Go code formatting
        run: gofmt -e main.go

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Initialize Go module
        run: go mod init github.com/popilmv/app1-go

      - name: Install dependencies
        run: go get github.com/gorilla/mux

      - name: Build Go project
        run: go build

